# Generated by Django 5.0.3 on 2024-03-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelOptions(
            name='user_equipment',
            options={'verbose_name': 'EquipoUsuario', 'verbose_name_plural': 'EquipoUsuario'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='disk',
            field=models.IntegerField(default=0, help_text='Gigabytes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='memory',
            field=models.IntegerField(default=0, help_text='Gigabytes'),
        ),
    ]
