# Generated by Django 5.0.3 on 2024-03-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_brand_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
