# Generated by Django 5.0.3 on 2024-03-21 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_equipment_rental_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='disk',
            field=models.IntegerField(default=0, help_text='Gigabytes', verbose_name='disco'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='memory',
            field=models.IntegerField(default=0, help_text='Gigabytes', verbose_name='memoria'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='processor',
            field=models.CharField(max_length=150, verbose_name='procesador'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='reference',
            field=models.CharField(max_length=150, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha final de alquiler'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha inicio de alquiler'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.type', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.TextField(verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user_equipment',
            name='assignment_date',
            field=models.DateField(verbose_name='fecha de asignacion'),
        ),
        migrations.AlterField(
            model_name='user_equipment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='user_equipment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='user_equipment',
            name='delivery_date',
            field=models.DateField(verbose_name='fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='user_equipment',
            name='equipment',
            field=models.ForeignKey(limit_choices_to={'in_use': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment', verbose_name='equipo'),
        ),
        migrations.AlterField(
            model_name='user_equipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
